### ISSUE TITLE
rename "filename"  to "population"

### ISSUE THREAD

**Issue by fnaji** [tercen/flowjo_plugin#56] opened 2021-12-14 14:24 UTC
When you upload multiple populations, it uses a fixed name called "filename",  "population" is more exact.

**Comment by martin1english** [comment] 2022-01-12 17:28
@MahoNagasawa  Can we close this issue? I don't know what to test.

**Comment by MahoNagasawa** [comment] 2022-01-13 09:25
@martin1english if this is not back to "filename", some of the data steps gives error because the template was using "filename" . if this name is back to "filename" from "population" the red dot shouldn't appear anymore. Then we can close this issue.

**Comment by ginberg** [comment] 2022-01-18 08:42
Maho confirmed that "filename" is back

**Closed as completed by ginberg** 2022-01-18 08:42 UTC
